stages:
  full_pipeline:
    cmd: cd notebooks && if not exist _executed mkdir _executed && papermill ml_pipeline.ipynb _executed/ml_pipeline_out.ipynb
    deps:
      - notebooks/ml_pipeline.ipynb
      - data/raw/CEE_DATA.arff
    outs:
      - notebooks/_executed/ml_pipeline_out.ipynb
      - data/intermediate/df.pkl
      - data/processed/Xy_train_resampled.pkl
      - data/processed/Xy_test.pkl
      - models/
      - reports/models_summary/
