stages:
  eda:
    cmd: cd notebooks && mkdir -p _executed && papermill 00_eda_ds.ipynb _executed/00_eda_ds_out.ipynb
    deps:
      - notebooks/00_eda_ds.ipynb
      - data/raw/CEE_DATA.arff
      - data/intermediate/df.pkl
    outs:
      - notebooks/_executed/00_eda_ds_out.ipynb
   
  data_engineering:
    cmd: cd notebooks && mkdir -p _executed && papermill 01_data_engineering.ipynb _executed/01_data_engineering_out.ipynb
    deps:
      - notebooks/01_data_engineering.ipynb
      - notebooks/_executed/00_eda_ds_out.ipynb
    outs:
      - notebooks/_executed/01_data_engineering_out.ipynb

  feature_engineering:
    cmd: cd notebooks && mkdir -p _executed && papermill 02_feature_engineering.ipynb _executed/02_feature_engineering_out.ipynb
    deps:
      - notebooks/02_feature_engineering.ipynb
      - notebooks/_executed/01_data_engineering_out.ipynb
    outs:
      - notebooks/_executed/02_feature_engineering_out.ipynb

  model_training:
    cmd: cd notebooks && mkdir -p _executed && papermill 03_model_training.ipynb _executed/03_model_training_out.ipynb
    deps:
      - notebooks/03_model_training.ipynb
      - notebooks/_executed/02_feature_engineering_out.ipynb
    outs:
      - notebooks/_executed/03_model_training_out.ipynb

  