stages:
  full_pipeline:
    cmd: python src/pipelines/ml_pipeline.py
    deps:
      - src/pipelines/ml_pipeline.py
      - src/data/load_data.py
      - src/features/feature_engineering.py
      - src/models/train_models.py
      - src/models/mlflow.py
      - src/visualization/plot_utils.py
      - data/raw/CEE_DATA.arff
    outs:
      - models/
      - results/
      - mlruns/